// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bywimfvrbcjcktqzdvmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5d2ltZnZyYmNqY2t0cXpkdm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NjAxNzYsImV4cCI6MjA2ODAzNjE3Nn0.pbscMiJ7N5lBqTsy9vkODlyv0it34dE2m1y4eV6Oclw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});